#!/usr/bin/env node
process
  .on('unhandledRejection', (reason, p) => {
    console.error(reason, 'Unhandled Rejection at Promise', p)
  })
  .on('uncaughtException', err => {
    console.error(err, 'Uncaught Exception thrown')
    process.exit(1)
  })

const program = require('yargs')
  .command(require('./src/cli/setup'))
  .command(require('./src/cli/new'))
  .command(require('./src/cli/upload'))
  .command(require('./src/cli/download'))
  .command(require('./src/cli/stats'))
  .command(require('./src/cli/remove'))
  .option('verbose', {
    alias: 'v',
    default: false
  })
  .argv

module.exports = program
